apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::423623831313:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-McbH0FpOUrjR
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::423623831313:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: '2024-09-10T06:17:29Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1314'
  uid: dd1be4c8-7cc9-4424-a2f8-8660ce6e43bc
